---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: user-

bases:
  - ../../base

commonLabels:
  app: user-dendrite

patches:
- patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: userapi
  target:
    kind: Deployment