apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinny-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cinny
  template:
    metadata:
      labels:
        app: cinny
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - cinny
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: cinny
        image: cinny:latest
        resources:
          request:
            memory: "150Mi"
            cpu: "20m"
          limits:
            memory: "250Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
          name: http