apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cinny

commonLabels:
  app: cinny

configurations:
- https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml


resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

images:
- digest: sha256:bc38bd967151fbfbbc821ed7f2b04f96eb8ec8afbe20ae14a6c9f4e74466b898
  name: cinny
  newName: ghcr.io/simon-boyer/cinny
