apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cinny

commonLabels:
  app: cinny

configurations:
- https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml


resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

images:
- digest: sha256:80aee6533546fdcd2e2bd2716c82206bf9fab7c1fa45d02864425ed9e8eb5878
  name: cinny
  newName: ghcr.io/simon-boyer/cinny
