apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cinny

commonLabels:
  app: cinny

configurations:
- https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml


resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

images:
- digest: sha256:0e7add806ce14c48f07ff54e1ddf3e26b5d4de5b92744a329642a9b1cccd5add
  name: cinny
  newName: ghcr.io/simon-boyer/cinny
