apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cinny

commonLabels:
  app: cinny

configurations:
- https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml


resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

images:
- digest: sha256:c3ac2a398a191abe6458d1f252cc6ae6a4019993e94a4a2a0d041c3f4fc9491e
  name: cinny
  newName: ghcr.io/simon-boyer/cinny
