deployment:
    enabled: true
providers:
      kubernetesCRD:
        enabled: true
      kubernetesIngress:
        enabled: true
ports:
  web:
    port: 80
    expose: true
    exposedPort: 80
    protocol: TCP
  websecure:
    port: 443
    expose: true
    exposedPort: 443
    protocol: TCP
    tls:
      enabled: true
      certResolver: le
      domains:
        - main: arctiq.codegameeat.com
certResolvers:
  le:
    email: traefik.uj4zj@simplelogin.co
    storage: /data/acme.json
    dnsChallenge:
      provider: cloudflare
env:
  - name: CLOUDFLARE_DNS_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api
        key: apikey
service:
      enabled: true
      type: LoadBalancer
securityContext:
  capabilities:
    drop: [ALL]
    add: [NET_BIND_SERVICE]
  readOnlyRootFilesystem: true
  runAsGroup: 0
  runAsNonRoot: false
  runAsUser: 0