apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik

resources:
  - namespace.yaml

helmCharts:
- name: traefik
  includeCRDs: true
  namespace: traefik
  releaseName: traefik
  version: 19.0.4
  repo: https://helm.traefik.io/traefik
  valuesInline:
    deployment:
      enabled: true
    providers:
          kubernetesCRD:
            enabled: true
          kubernetesIngress:
            enabled: true
    ports:
      web:
       port: 80
       expose: true
       exposedPort: 80
       protocol: TCP
      websecure:
        port: 443
        expose: true
        exposedPort: 443
        protocol: TCP
        tls:
          enabled: true
          certResolver: le
          domains:
            - main: 34.152.59.49.nip.io
    certResolvers:
      le:
        acme:
          email: traefik.uj4zj@simplelogin.co
          storage: /data/acme.json
          httpChallenge:
            entryPoint: web
    service:
          enabled: true
          type: LoadBalancer
    securityContext:
      capabilities:
        drop: [ALL]
        add: [NET_BIND_SERVICE]
      readOnlyRootFilesystem: true
      runAsGroup: 0
      runAsNonRoot: false
      runAsUser: 0