apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`matrix.arctiq.codegameeat.com`) && PathPrefix(`/_matrix/media`)
      services:
        - name: service
          port: external
  tls:
    certResolver: le