---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: media-

bases:
  - ../../base

commonLabels:
  app: media-dendrite

patches:
- patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: mediaapi
  target:
    kind: Deployment