---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dendrite

configMapGenerator:
  - name: nginx-conf
    files:
      - nginx.conf

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml