apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-mesh
spec:
  project: default
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/Simon-Boyer/arctiq-mission-infra'
    path: kube-tools/traefik-mesh
  syncPolicy:
    automated:
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
spec:
  project: default
  destination:
    namespace: crossplane-system
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/Simon-Boyer/arctiq-mission-infra'
    path: kube-tools/crossplane
  syncPolicy:
    automated:
      selfHeal: true
      