apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts
  source:
    chart: argo-rollouts
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 2.21.1
    helm:
      releaseName: argo-rollouts
      parameters:
        - name: dashboard.enabled
          value: "true"
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-mesh
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  source:
    chart: traefik-mesh
    repoURL: https://helm.traefik.io/mesh
    targetRevision: 4.1.0
    helm:
      releaseName: traefik-mesh 
      parameters:
        - name: kubedns
          value: "true"
  syncPolicy:
    automated:
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-helm
spec:
  project: default
  destination:
    namespace: crossplane-system
    server: https://kubernetes.default.svc
  source:
    chart: crossplane
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.10.1
    helm:
      releaseName: crossplane
  syncPolicy:
    automated:
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-pkgs
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  destination:
    namespace: crossplane-system
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/Simon-Boyer/arctiq-mission-infra'
    path: kube-tools/crossplane/pkg-configs
  syncPolicy:
    automated:
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-providers
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  destination:
    namespace: crossplane-system
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/Simon-Boyer/arctiq-mission-infra'
    path: kube-tools/crossplane/providers
  syncPolicy:
    automated:
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-generator-helm
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    chart: kubernetes-secret-generator
    repoURL: https://helm.mittwald.de
    targetRevision: 3.4.0
    helm:
      releaseName: kubernetes-secret-generator
  syncPolicy:
    automated:
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cinny
spec:
  project: default
  source:
    repoURL: 'https://github.com/Simon-Boyer/arctiq-mission-infra'
    path: apps/cinny
  destination:
    server: https://kubernetes.default.svc
    namespace: cinny
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dendrite
spec:
  project: default
  source:
    repoURL: 'https://github.com/Simon-Boyer/arctiq-mission-infra'
    path: apps/dendrite
  destination:
    server: https://kubernetes.default.svc
    namespace: dendrite
  syncPolicy:
    automated:
      prune: true
      selfHeal: true