apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-mesh
spec:
  project: default
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/Simon-Boyer/arctiq-mission-infra'
    path: kube-tools/traefik-mesh
  syncPolicy:
    automated:
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-helm
spec:
  project: default
  destination:
    namespace: crossplane-system
    server: https://kubernetes.default.svc
  source:
    chart: crossplane
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.10.1
    helm:
      releaseName: crossplane
  syncPolicy:
    automated:
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
annotations:
    argocd.argoproj.io/sync-wave: "1"
metadata:
  name: crossplane-defs
spec:
  project: default
  destination:
    namespace: crossplane-system
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/Simon-Boyer/arctiq-mission-infra'
    path: kube-tools/crossplane
  syncPolicy:
    automated:
      selfHeal: true
      