apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - project.yaml
  - applications.yaml
  - ingress.yaml

patches:
- patch: |-
      - op: add
        path: /data
        value:
          kustomize.buildOptions: --load-restrictor LoadRestrictionsNone --enable-helm
          server.insecure: "true"
  target:
    kind: ConfigMap
    name: argocd-cm