apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik

resources:
  - namespace.yaml

helmCharts:
- name: traefik-mesh
  includeCRDs: true
  namespace: traefik
  releaseName: traefik-mesh
  version: 4.1.0
  repo: https://helm.traefik.io/mesh
  valuesInline:
    kubedns: true