apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crossplane-system

resources:
  - namespace.yaml
  - gcp-pkg-config.yaml
  - providers.yaml

helmCharts:
- name: crossplane
  includeCRDs: true
  releaseName: crossplane
  version: 1.10.1
  repo: https://charts.crossplane.io/stable