apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dendrite

resources:
- deployment.yaml
- service.yaml

configMapGenerator:
- files:
  - dendrite.yaml
  name: dendrite-cm

images:
- digest: sha256:4ddb09f88762bb394e68e65ad4a6f08ca9d618b642030be38b778333fd1312d4
  name: dendrite
  newName: ghcr.io/simon-boyer/dendrite
