---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dendrite

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: dendrite-cm
    files:
      - dendrite.yaml

images:
  - name: dendrite
    newName: ghcr.io/simon-boyer/dendrite
    digest: sha256:ae761105a604727b5e81603d62cc92e708b4e4dcf1b6ae49b1778b6f685d4045