apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dendrite

resources:
- deployment.yaml
- service.yaml

configMapGenerator:
- files:
  - dendrite.yaml
  name: dendrite-cm

images:
- digest: sha256:47c9864f894a2cce5fe448e39a6deebbe0b2e60f5291007f2c6378dbc98db044
  name: dendrite
  newName: ghcr.io/simon-boyer/dendrite
